name: Transfer
author: TheRoyalBlock
api: 3.0.0-ALPHA10
version: 1.0
main: Royal\Main

# Commands: If your plugin has commands: Do this:
command:
    addnpc:
        description: Add a NPC
        usage: /addnpc npcname