
# PurePerms by 64FF00 (xktiverz@gmail.com, @64ff00 for Twitter)

name: Transfer
main: _64FF00\PurePerms\Transfer
version: "1.4.0-INDEV"
api:
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
load: POSTWORLD
commands:
  addnpc:
      description: "Add a NPC"