name: Transfer
author: TheRoyalBlock
api: [1.0.0, 2.0.0, 3.0.0, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 4.0.0]
version: 1.0
main: _64FF00\PurePerms\Main

# Commands: If your plugin has commands: Do this:
command:
    addnpc:
        description: Add a NPC
        usage: /addnpc npcname